# Use postgres/example user/password credentials
version: '3.8'

services:
  postgres:
    container_name: postgres
    build:
      context: ./docker_settings/database
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pglogs:/logs

  api:
    container_name: api
    build:
      context: .
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - node-modules:/usr/app/node_modules
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  logs:
  pgdata:
  app:
  node-modules:
